apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitops-workshop
  name: gitops-workshop-service
spec:
  type: LoadBalancer
  selector:
    app: gitops-workshop
  ports:
  - name: http
    port: 8082
    protocol: TCP
    targetPort: 80
status:
  loadBalancer: {}