apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: gitops-workshop
  name:  gitops-workshop-application
spec:
  project: gitops-workshop-project
  source:
    repoURL: https://github.com/verburg95/gitops-workshop-infra
    targetRevision: main
    path: .
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true